services:
  artesanias-commerce-service:
    image: brayan22/artesanias-commerce-service:latest
    environment:
      - CONFIG_SERVER_URL=http://artesanias-config-server:9196
      - JDBC_DATABASE_URL=jdbc:postgresql://artesanias-database:5432/artesanias
      - JDBC_DATABASE_USERNAME=postgres
      - JDBC_DATABASE_PASSWORD=artesanias
      - COMMERCE_SERVICE_PORT=9090
      - HOST=http://artesanias.localhost
      - EUREKA_URI=http://artesanias-discovery-server:8761/eureka/
      - HOSTNAME=artesanias-commerce-service
    hostname: artesanias-commerce-service
    networks:
      - backend
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
networks:
  backend:
    external: true